### PR TITLE
Add BattlEye stuff

### PR DESCRIPTION
**Pull request by andreasclaesson**
Since V updated and installed BattlEye in the latest update as anti-cheat, it shouldn't be removed

### CODE REVIEW

**Comment by Crohnus1965** [comment]
File to leave in game Dir:       GTA5_BE.exe
Folder to leave in game Dir:   BattlEye

**Comment by ganeshh123** [comment]
Thanks, appreciate it! I'll try and build a new release tomorrow.

**Comment by Crohnus1965** [comment]
also, libtox.dll can be left in game Dir also.  Either Cli, or tox protocol. Best i could find, is in epic, steam, and r* launcher files.

**Comment by ganeshh123** [comment]
> also, libtox.dll can be left in game Dir also. has something to do with video decoding.

Can you open a separate PR and I can rake a look tomorrow, thanks!

**Comment by ganeshh123** [comment]
I did it, no need anymore.

**Pull request merged**
